version: 2.0.0-{build}

os: Windows Server 2012 R2

shallow_clone: true

environment:
  TURBO_ROOT: C:\turbo.lua

  matrix:
  - platform: x64

#cache:

init:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%'
  - SET PATH=%PATH%;C:\MinGW\bin;%TURBO_ROOT%;%TURBO_ROOT%\luarocks\2.2;%TURBO_ROOT%\rocks\bin;

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir %TURBO_ROOT%
  - mkdir %TURBO_ROOT%\src
  - cd %TURBO_ROOT%\src
  # Build LuaJIT 2.
  - git clone http://luajit.org/git/luajit-2.0.git
  - cd %TURBO_ROOT%\src\luajit-2.0\src
  - call msvcbuild
  - cp luajit.exe %TURBO_ROOT%
  - cp lua51.dll %TURBO_ROOT%
  - SET LUA_PATH=%TURBO_ROOT%\rocks\share\lua\5.1\?.lua;%TURBO_ROOT%\rocks\share\lua\5.1\?\init.lua;%TURBO_ROOT%\src\turbo\?.lua;%TURBO_ROOT%\src\turbo\turbo\?.lua
  - SET LUA_CPATH=%TURBO_ROOT%\rocks\lib\lua\5.1\?.dll
  # Install LuaRocks from github head.
  - cd C:\turbo.lua\src
  - mkdir rocks
  - git clone https://github.com/keplerproject/luarocks.git
  - cd C:\turbo.lua\src\luarocks
  - call install.bat /TREE %TURBO_ROOT%\rocks\ /P %TURBO_ROOT%\luarocks\ /INC %TURBO_ROOT%\src\luajit-2.0\src /LIB %TURBO_ROOT%\src\luajit-2.0\src /LUA %TURBO_ROOT% /Q
  # Install Lua deps.
  - call luarocks install luasocket
  - call luarocks install luafilesystem
  - call luarocks install busted

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mingw32-make SSL=none
  - mv libtffi_wrap.so libtffi_wrap.dll
  - SET TURBO_LIBTFFI=%APPVEYOR_BUILD_FOLDER%\libtffi_wrap.dll

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - busted
